# @package _group_

_target_: rxnrep.data.green.GreenRegressionDataModule
trainset_filename: /Users/mjwen/Documents/Dataset/activation_energy_Green/wb97xd3_n200_processed_train.tsv
valset_filename: /Users/mjwen/Documents/Dataset/activation_energy_Green/wb97xd3_n200_processed_train.tsv
testset_filename: /Users/mjwen/Documents/Dataset/activation_energy_Green/wb97xd3_n200_processed_train.tsv

batch_size: 100
num_workers: 0
pin_memory: True
state_dict_filename: dataset_state_dict.yaml
