# @package _group_

_target_: rxnrep.data.nrel.NRELDataModule
trainset_filename: /Users/mjwen/Documents/Dataset/NREL_BDE/rdf_data_190531_n200_processed_train.tsv
valset_filename: /Users/mjwen/Documents/Dataset/NREL_BDE/rdf_data_190531_n200_processed_val.tsv
testset_filename: /Users/mjwen/Documents/Dataset/NREL_BDE/rdf_data_190531_n200_processed_test.tsv

batch_size: 100
num_workers: 0
pin_memory: True
state_dict_filename: dataset_state_dict.yaml
