name: Python package

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 3
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Include $CONDA in $PATH
      run: echo ::add-path::$CONDA/bin
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        conda install pytorch==1.6.0 torchvision cpuonly -c pytorch
        conda install dgl==0.5.2 -c dglteam
        conda install pymatgen==2020.8.13 -c conda-forge
        conda install rdkit==2020.03.5 -c conda-forge
        conda install openbabel==3.1.1 -c conda-forge
        conda install pytorch-lightning -c conda-forge pytorch-lightning
        pip install -e .
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pip install pytest
        pytest -s
