# @package _group_

booster: dart
eta: 0.3
gamma: 0.3
max_depth: 6
min_child_width: 5
colsample_bytree: 0.5
colsample_bylevel: 0.5
subsample: 1.
sampling_method: gradient
scale_pos_weight: 1.
rate_drop: 0.
tree_method: gpu_hist
objective: multi:softmax
num_round: 100
num_early_stopping_round: 20