# @package _group_

_target_: rxnrep.data.electrolyte.ElectrolyteContrastiveDataModule
trainset_filename: /Users/mjwen/Documents/Dataset/electrolyte/reactions_n2000_train.json
valset_filename: /Users/mjwen/Documents/Dataset/electrolyte/reactions_n2000_val.json
testset_filename: /Users/mjwen/Documents/Dataset/electrolyte/reactions_n2000_test.json

batch_size: 100
num_workers: 0
pin_memory: True
state_dict_filename: dataset_state_dict.yaml
