# @package _group_

_target_: rxnrep.data.green.GreenContrastiveDataModule
trainset_filename: /Users/mjwen/Documents/Dataset/activation_energy_Green/wb97xd3_processed_has_reverse-False_rmg_family_10_class_n200.tsv
valset_filename: /Users/mjwen/Documents/Dataset/activation_energy_Green/wb97xd3_processed_has_reverse-False_rmg_family_10_class_n200.tsv
testset_filename: /Users/mjwen/Documents/Dataset/activation_energy_Green/wb97xd3_processed_has_reverse-False_rmg_family_10_class_n200.tsv

batch_size: 100
num_workers: 0
pin_memory: True
state_dict_filename: dataset_state_dict.yaml
restore_state_dict_filename: null # this will be overwriteen by in config adaptor

# transform1 and transform2 provided in main config
