# @package _group_

_target_: rxnrep.data.heid.HeidContrastiveDataModule
# The path is relative to run.py. "../../../" to overcome the change of cwd by hydra,
# which changes cwd to something like "outputs/2021-11-21/15-21-02/" in the same
# directory as run.py. In practice, just provide an absolute path.
trainset_filename: /Users/mjwen/Documents/Dataset/Heid_reaction_dataset/lograte_processed_val.tsv
valset_filename: /Users/mjwen/Documents/Dataset/Heid_reaction_dataset/lograte_processed_val.tsv
testset_filename: /Users/mjwen/Documents/Dataset/Heid_reaction_dataset/lograte_processed_val.tsv

batch_size: 500
num_workers: 0
pin_memory: True
state_dict_filename: dataset_state_dict.yaml
restore_state_dict_filename: null # this will be overwriteen by in config adaptor
remove_H: false
# transform1 and transform2 provided in main config
