# @package _group_

_target_: rxnrep.data.uspto.UsptoContrastiveDataModule
trainset_filename: /Users/mjwen/Documents/Dataset/uspto/Schneider50k/schneider50k_n400_processed_train.tsv
valset_filename: /Users/mjwen/Documents/Dataset/uspto/Schneider50k/schneider50k_n400_processed_train.tsv
testset_filename: /Users/mjwen/Documents/Dataset/uspto/Schneider50k/schneider50k_n400_processed_train.tsv

batch_size: 100
num_workers: 0
pin_memory: True
state_dict_filename: dataset_state_dict.yaml

# transform1 and transform2 provided in main config