# to create a conda environment, run $ conda env create -f environment.yml
name: rxnrep
channels:
  - pytorch
  - dglteam
  - conda-forge
  - defaults
dependencies:
  - omegaconf
  - pymatgen==2020.8.13
  - rdkit==2020.03.5
  - openbabel==3.1.1
  - pytorch==1.8.0
  - dgl==0.6.0
