# @package _group_

_target_: rxnrep.data.uspto.UsptoMorganDataModule
trainset_filename: /Users/mjwen/Documents/Dataset/uspto/Schneider50k/schneider50k_n400_processed_train.tsv
valset_filename: /Users/mjwen/Documents/Dataset/uspto/Schneider50k/schneider50k_n400_processed_train.tsv
testset_filename: /Users/mjwen/Documents/Dataset/uspto/Schneider50k/schneider50k_n400_processed_train.tsv
num_reaction_classes: 46

# morgan feats params
morgan_radius: 2
morgan_size: 2048
feature_combine_method: difference

# data loader
batch_size: 100
num_workers: 0
pin_memory: True
