# @package _group_

# this should only contain the decoder part, the encoder part is in encoder.yaml
cfg_adjuster:
  _target_: rxnrep.model.classifier_morgan.adjust_config

model_class:
  _target_: rxnrep.model.classifier_morgan.LightningModel
  reaction_type_decoder_num_layers: 2
  activation: ReLU
