# @package _group_

# this should only contain the decoder part, the encoder part is in encoder.yaml

cfg_adjuster:
  _target_: rxnrep.scripts.train_classification.adjust_config

model_class:
  _target_: rxnrep.scripts.train_classification.LightningModel
  # reaction_type_decoder_hidden_layer_sizes:
  reaction_type_decoder_num_layers: 2
