# @package _group_

cfg_adjuster:
  _target_: rxnrep.model.pretrainer.adjust_config

model_class:
  _target_: rxnrep.model.pretrainer.LightningModel
  simclr_temperature: 0.1
  simclr_decoder_num_layers: 2
