# @package _group_

# this should only contain the decoder part, the encoder part is in encoder.yaml
cfg_adjuster:
  _target_: rxnrep.model.regressor_act_energy.adjust_config

model_class:
  _target_: rxnrep.model.regressor_act_energy.LightningModel
  activation_energy_decoder_num_layers: 2

