# @package _group_

#
# encoder part for all models
#

conv: GatedGCNConv # GINConvGlobal, GINConvOriginal, GATConvGlobal
embedding_size: null # type: int. Feature size to map input features to, before feeding to conv layers. Default to `conv_layer_size`
conv_layer_size: 64 # type: int. Size of molecule and reaction conv layers.
activation: ReLU

# molecule conv
molecule_num_fc_layers: 2 # type: int. Size of MLP layers to in conv module.
molecule_batch_norm: True
molecule_residual: True
molecule_dropout: 0.0 # type: float.
num_mol_conv_layers: 2

# Method to combine reactants and features to form reactions features.
combine_reactants_products: difference # dtype: str, [`difference`|`concatenate`].
