# @package _group_

# no monitor, no early stopping, save checkpoint every 10 epochs

model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  save_last: True # additionally always save model from last epoch
  verbose: False
  save_top_k: -1 # save k best models (-1 for all) every `every_n_epochs` epoch
  every_n_val_epochs: 10