# @package _group_

_target_: rxnrep.data.transforms.Subgraph
ratio: 0.2
select_mode: ratio
ratio_multiplier: out_center
reaction_center_mode: functional_group
functional_group_smarts_filenames: /home/hgf_dlr/hgf_nmr5289/profile/rxnrep/assets/smarts_daylight.tsv
