# main config file

defaults:
  - model/encoder: encoder.yaml
  - model/decoder: classifier.yaml

  - datamodule: predictive/schneider.yaml

  # training
  - optimizer: adams.yaml

  # lightning settings
  - trainer: default.yaml
  - trainer: minimal.yaml # this will be combined with trainer: default.yaml

  - logger: wandb.yaml
  - callbacks: default.yaml

# other configs
restore: True
seed: 35
git_repo_path: null # path to this git repo
skip_test: False # skip running model against test set after training finishes
finetune: False # whether this is a finetune model @@@TODO maybe determine it automatically
